alias:
    - confuzzius
    #- echidna
    - maian
    - manticore
    - mythril
    - securify
    - slither
    - smartcheck
    - conkas
    - ethainter
    - ethor
    - honeybadger
    - madmax
    - oyente
    - osiris
    - semgrep
    - sfuzz
    - solhint


# Tools to adapt to the argument orchestrator

# Conkas                                            ADDED
# eThor                                             ADDED
# Ethainter                                         ADDED
# HoneyBadger (based on Onyente)                    ADDED
# Madmax (gigahorse toolchain)                      ADDED
# Osiris                                            ADDED
# Oyente                                            ADDED
# Semgrep                                           ADDED
# sFuzz                                             ADDED
# Solhint                                           ADDED
# teEther
# Vandal


#TODO Fare dei test sui 4 split utilizzando smartbugs originale con tutti i tool