alias:
    - confuzzius
    #- echidna
    - maian
    - manticore
    - mythril
    - securify
    - slither
    - smartcheck
    - conkas
    - ethainter
    - ethor
    - honeybadger
    - madmax
    - oyente
    - osiris
    - semgrep
    - sfuzz
    - solhint


# Actively supported tools:

# Conkas                                            ADDED
# eThor                                             ADDED
# Ethainter                                         ADDED
# HoneyBadger (based on Onyente)                    ADDED
# Madmax (gigahorse toolchain)                      ADDED
# Osiris
# Oyente                                            ADDED
# Semgrep
# sFuzz
# Solhint
# teEther
# Vandal



# Tools still supported but not 100%:

# Manticore (Progetto in mantenimento, non verrà aggiornato per un po' ma funziona)



# Tools not actively supported anymore:

# Securify (rimpiazzato da securify 2.0)
# Smartcheck (apparentemente inutili per versioni di solc > 0.6.0)


#TODO Fare dei test sui 4 split utilizzando smartbugs originale con tutti i tool scaricati oggi