alias:
    - confuzzius    
    - maian
    - manticore
    - mythril
    - securify
    - slither
    - smartcheck
    - conkas
    - ethainter
    - ethor
    - honeybadger
    - madmax
    - oyente
    - osiris
    - semgrep
    - sfuzz
    - solhint



#NOTE: eThor has been added in the orchestrator, but then commented out because I think it may not be necessary given the contexts in which it should be used

#NOTE: Semgrep has not been orchestrated. I need to investigate the results of the original smartbugs to determine exactly if and where it should be placed

#NOTE: sfuzz CURRENTLY ON HOLD. I have to determine if i need another fuzzer